CODE_PAGES: dict[int, dict[int, str]] = {
    0: {
        0x05: "Sync",
        0x06: "Responses",
        0x07: "Add",
        0x08: "Change",
        0x09: "Delete",
        0x0A: "Fetch",
        0x0B: "SyncKey",
        0x0D: "ServerId",
        0x0E: "Status",
        0x0F: "Collection",
        0x10: "Class",
        0x12: "CollectionId",
        0x13: "GetChanges",
        0x14: "MoreAvailable",
        0x15: "WindowSize",
        0x16: "Commands",
        0x17: "Options",
        0x18: "FilterType",
        0x1C: "Collections",
        0x1D: "ApplicationData",
        0x1E: "DeletesAsMoves",
        0x20: "Supported",
        0x21: "SoftDelete",
    },
    2: {
        0x05: "Attachment",
        0x06: "Attachments",
        0x07: "AttName",
        0x08: "AttSize",
        0x09: "Att0Id",
        0x0A: "AttMethod",
        0x0C: "Body",
        0x0D: "BodySize",
        0x0E: "BodyTruncated",
        0x0F: "DateReceived",
        0x10: "DisplayName",
        0x11: "DisplayTo",
        0x12: "Importance",
        0x13: "MessageClass",
        0x14: "Subject",
        0x15: "Read",
        0x16: "To",
        0x17: "Cc",
        0x18: "From",
        0x19: "ReplyTo",
        0x1A: "AllDayEvent",
        0x1B: "Categories",
        0x1C: "Category",
        0x1D: "DtStamp",
        0x1E: "EndTime",
        0x1F: "InstanceType",
        0x20: "BusyStatus",
        0x21: "Location",
        0x22: "MeetingRequest",
        0x23: "Organizer",
        0x24: "RecurrenceId",
        0x25: "Reminder",
        0x26: "ResponseRequested",
        0x27: "Recurrences",
        0x28: "Recurrence",
        0x29: "Type",
        0x2A: "Until",
        0x2B: "Occurrences",
        0x2C: "Interval",
        0x2D: "DayOfWeek",
        0x2E: "DayOfMonth",
        0x2F: "WeekOfMonth",
        0x30: "MonthOfYear",
        0x31: "StartTime",
        0x32: "Sensitivity",
        0x33: "TimeZone",
        0x34: "GlobalObjId",
        0x35: "ThreadTopic",
        0x36: "MIMEData",
        0x37: "MIMETruncated",
        0x38: "MIMESize",
        0x39: "InternetCPID",
        0x3A: "Flag",
        0x3B: "Status",
        0x3C: "ContentClass",
        0x3D: "FlagType",
        0x3E: "CompleteTime",
        0x3F: "DisallowNewTimeProposal",
    },
    7: {
        0x07: "DisplayName",
        0x08: "ServerId",
        0x09: "ParentId",
        0x0A: "Type",
        0x0C: "Status",
        0x0E: "Changes",
        0x0F: "Add",
        0x10: "Delete",
        0x11: "Update",
        0x12: "SyncKey",
        0x13: "FolderCreate",
        0x14: "FolderDelete",
        0x15: "FolderUpdate",
        0x16: "FolderSync",
        0x17: "Count",
    },
    14: {
        0x05: "Provision",
        0x06: "Policies",
        0x07: "Policy",
        0x08: "PolicyType",
        0x09: "PolicyKey",
        0x0A: "Data",
        0x0B: "Status",
        0x0C: "RemoteWipe",
        0x0D: "EASProvisionDoc",
        0x0E: "DevicePasswordEnabled",
        0x0F: "AlphanumericDevicePasswordRequired",
        0x10: "RequireStorageCardEncryption",
        0x11: "PasswordRecoveryEnabled",
        0x13: "AttachmentsEnabled",
        0x14: "MinDevicePasswordLength",
        0x15: "MaxInactivityTimeDeviceLock",
        0x16: "MaxDevicePasswordFailedAttempts",
        0x17: "MaxAttachmentSize",
        0x18: "AllowSimpleDevicePassword",
        0x19: "DevicePasswordExpiration",
        0x1A: "DevicePasswordHistory",
        0x1B: "AllowStorageCard",
        0x1C: "AllowCamera",
        0x1D: "RequireDeviceEncryption",
        0x1E: "AllowUnsignedApplications",
        0x1F: "AllowUnsignedInstallationPackages",
        0x20: "MinDevicePasswordComplexCharacters",
        0x21: "AllowWiFi",
        0x22: "AllowTextMessaging",
        0x23: "AllowPOPIMAPEmail",
        0x24: "AllowBluetooth",
        0x25: "AllowIrDA",
        0x26: "RequireManualSyncWhenRoaming",
        0x27: "AllowDesktopSync",
        0x28: "MaxCalendarAgeFilter",
        0x29: "AllowHTMLEmail",
        0x2A: "MaxEmailAgeFilter",
        0x2B: "MaxEmailBodyTruncationSize",
        0x2C: "MaxEmailHTMLBodyTruncationSize",
        0x2D: "RequireSignedSMIMEMessages",
        0x2E: "RequireEncryptedSMIMEMessages",
        0x2F: "RequireSignedSMIMEAlgorithm",
        0x30: "RequireEncryptionSMIMEAlgorithm",
        0x31: "AllowSMIMEEncryptionAlgorithmNegotiation",
        0x32: "AllowSMIMESoftCerts",
        0x33: "AllowBrowser",
        0x34: "AllowConsumerEmail",
        0x35: "AllowRemoteDesktop",
        0x36: "AllowInternetSharing",
        0x37: "UnapprovedInROMApplicationList",
        0x38: "ApplicationName",
        0x39: "ApprovedApplicationList",
        0x3A: "Hash",
    },
    17: {
        0x05: "BodyPreference",
        0x06: "Type",
        0x07: "TruncationSize",
        0x08: "AllOrNone",
        0x0A: "Body",
        0x0B: "Data",
        0x0C: "EstimatedDataSize",
        0x0D: "Truncated",
        0x0E: "Attachments",
        0x0F: "Attachment",
        0x10: "DisplayName",
        0x11: "FileReference",
        0x12: "Method",
        0x13: "ContentId",
        0x14: "ContentLocation",
        0x15: "IsInline",
        0x16: "NativeBodyType",
        0x17: "ContentType",
        0x18: "Preview",
        0x19: "BodyPartPreference",
        0x1A: "BodyPart",
        0x1B: "Status",
        0x1C: "Add",
        0x1D: "Delete",
        0x1E: "ClientId",
        0x1F: "Content",
        0x20: "Location",
        0x21: "Annotation",
        0x22: "Street",
        0x23: "City",
        0x24: "State",
        0x25: "Country",
        0x26: "PostalCode",
        0x27: "Latitude",
        0x28: "Longitude",
        0x29: "Accuracy",
        0x2A: "Altitude",
        0x2B: "AltitudeAccuracy",
        0x2C: "LocationUri",
        0x2D: "InstanceId",
    },
    20: {
        0x05: "ItemOperations",
        0x06: "Fetch",
        0x07: "Store",
        0x08: "Options",
        0x09: "Range",
        0x0A: "Total",
        0x0B: "Properties",
        0x0C: "Data",
        0x0D: "Status",
        0x0E: "Response",
        0x0F: "Version",
        0x10: "Schema",
        0x11: "Part",
        0x12: "EmptyFolderContents",
        0x13: "DeleteSubFolders",
        0x14: "UserName",
        0x15: "Password",
        0x16: "Move",
        0x17: "DstFldId",
        0x18: "ConversationId",
        0x19: "MoveAlways",
    },
    18: {
        0x05: "Settings",
        0x06: "Status",
        0x07: "Get",
        0x08: "Set",
        0x09: "Oof",
        0x0A: "OofState",
        0x0B: "StartTime",
        0x0C: "EndTime",
        0x0D: "OofMessage",
        0x0E: "AppliesToInternal",
        0x0F: "AppliesToExternalKnown",
        0x10: "AppliesToExternalUnknown",
        0x11: "Enabled",
        0x12: "ReplyMessage",
        0x13: "BodyType",
        0x14: "DevicePassword",
        0x15: "Password",
        0x16: "DeviceInformation",
        0x17: "Model",
        0x18: "IMEI",
        0x19: "FriendlyName",
        0x1A: "OS",
        0x1B: "OSLanguage",
        0x1C: "PhoneNumber",
        0x1D: "UserInformation",
        0x1E: "EmailAddresses",
        0x1F: "SMTPAddress",
        0x20: "UserAgent",
        0x21: "EnableOutboundSMS",
        0x22: "MobileOperator",
        0x23: "PrimarySmtpAddress",
        0x24: "Accounts",
        0x25: "Account",
        0x26: "AccountId",
        0x27: "AccountName",
        0x28: "UserDisplayName",
        0x29: "SendDisabled",
        0x2B: "RightsManagementInformation",
    },
    22: {
        0x05: "UmCallerID",
        0x06: "UmUserNotes",
        0x07: "UmAttDuration",
        0x08: "UmAttOrder",
        0x09: "ConversationId",
        0x0A: "ConversationIndex",
        0x0B: "LastVerbExecuted",
        0x0C: "LastVerbExecutionTime",
        0x0D: "ReceivedAsBcc",
        0x0E: "Sender",
        0x0F: "CalendarType",
        0x10: "IsLeapMonth",
        0x11: "AccountId",
        0x12: "FirstDayOfWeek",
        0x13: "MeetingMessageType",
        0x14: "IsDraft",
    },
    # Page 1 - Contacts
    1: {
        0x05: "Anniversary", 0x06: "AssistantName", 0x07: "AssistantPhoneNumber",
        0x08: "Birthday", 0x09: "Body", 0x0A: "BodySize", 0x0B: "BodyTruncated",
        0x0C: "Business2PhoneNumber", 0x0D: "BusinessAddressCity",
        0x0E: "BusinessAddressCountry", 0x0F: "BusinessAddressPostalCode",
        0x10: "BusinessAddressState", 0x11: "BusinessAddressStreet",
        0x12: "BusinessFaxNumber", 0x13: "BusinessPhoneNumber",
        0x14: "CarPhoneNumber", 0x15: "Categories", 0x16: "Category",
        0x17: "Children", 0x18: "Child", 0x19: "CompanyName",
        0x1A: "Department", 0x1B: "Email1Address", 0x1C: "Email2Address",
        0x1D: "Email3Address", 0x1E: "FileAs", 0x1F: "FirstName",
        0x20: "Home2PhoneNumber", 0x21: "HomeAddressCity",
        0x22: "HomeAddressCountry", 0x23: "HomeAddressPostalCode",
        0x24: "HomeAddressState", 0x25: "HomeAddressStreet",
        0x26: "HomeFaxNumber", 0x27: "HomePhoneNumber",
        0x28: "JobTitle", 0x29: "LastName", 0x2A: "MiddleName",
        0x2B: "MobilePhoneNumber", 0x2C: "OfficeLocation",
        0x2D: "OtherAddressCity", 0x2E: "OtherAddressCountry",
        0x2F: "OtherAddressPostalCode", 0x30: "OtherAddressState",
        0x31: "OtherAddressStreet", 0x32: "PagerNumber",
        0x33: "RadioPhoneNumber", 0x34: "Spouse", 0x35: "Suffix",
        0x36: "Title", 0x37: "WebPage", 0x38: "YomiCompanyName",
        0x39: "YomiFirstName", 0x3A: "YomiLastName",
        0x3B: "CompressedRTF", 0x3C: "Picture", 0x3D: "Alias",
        0x3E: "WeightedRank",
    },
    # Page 3 - Calendar
    3: {
        0x05: "Timezone", 0x06: "AllDayEvent", 0x07: "Attendees",
        0x08: "Attendee", 0x09: "Email", 0x0A: "Name", 0x0B: "DtStamp",
        0x0C: "EndTime", 0x0D: "InstanceType", 0x0E: "BusyStatus",
        0x0F: "Location", 0x10: "MeetingRequest", 0x11: "Organizer",
        0x12: "RecurrenceId", 0x13: "Reminder", 0x14: "ResponseRequested",
        0x15: "Recurrences", 0x16: "Recurrence", 0x17: "Type",
        0x18: "Until", 0x19: "Occurrences", 0x1A: "Interval",
        0x1B: "DayOfWeek", 0x1C: "DayOfMonth", 0x1D: "WeekOfMonth",
        0x1E: "MonthOfYear", 0x1F: "StartTime", 0x20: "Subject",
        0x21: "Sensitivity", 0x22: "Body", 0x23: "BodySize",
        0x24: "BodyTruncated", 0x25: "Categories", 0x26: "Category",
        0x27: "ResponseType", 0x28: "DisallowedRecurrencePatterns",
        0x29: "OnlineMeetingConfLink", 0x2A: "OnlineMeetingExternalLink",
    },
    # Page 4 - Move
    4: {
        0x05: "Move", 0x06: "Movements", 0x07: "SrcMsgId", 0x08: "SrcFldId",
        0x09: "DstFldId", 0x0A: "Response",
    },
    # Page 5 - GetItemEstimate
    5: {
        0x05: "GetItemEstimate", 0x06: "Version", 0x07: "Collections",
        0x08: "Collection", 0x09: "Class", 0x0A: "CollectionId",
        0x0B: "DateTime", 0x0C: "Estimate", 0x0D: "Response",
        0x0E: "Status", 0x0F: "FilterType",
    },
    # Page 6 - FolderHierarchy
    6: {
        0x05: "Folders", 0x06: "Folder", 0x07: "DisplayName",
        0x08: "ServerId", 0x09: "ParentId", 0x0A: "Type", 0x0B: "Response",
        0x0C: "Status", 0x0D: "ContentClass", 0x0E: "Changes",
        0x0F: "Add", 0x10: "Delete", 0x11: "Update", 0x12: "SyncKey",
        0x13: "FolderCreate", 0x14: "FolderDelete", 0x15: "FolderUpdate",
        0x16: "FolderSync", 0x17: "Count",
    },
    # Page 8 - ResolveRecipients
    8: {
        0x05: "ResolveRecipients", 0x06: "Response", 0x07: "Status",
        0x08: "Recipient", 0x09: "DisplayName", 0x0A: "EmailAddress",
        0x0B: "Certificates", 0x0C: "Certificate", 0x0D: "MiniCertificate",
        0x0E: "Options", 0x0F: "To", 0x10: "CertificateRetrieval",
        0x11: "RecipientCount", 0x12: "MaxCertificates", 0x13: "MaxAmbientRecipients",
        0x14: "CertificateCount", 0x15: "Availability",
        0x16: "StartTime", 0x17: "EndTime", 0x18: "MergedFreeBusy",
    },
    # Page 9 - Tasks
    9: {
        0x05: "Body", 0x06: "BodySize", 0x07: "BodyTruncated",
        0x08: "Categories", 0x09: "Category", 0x0A: "Complete",
        0x0B: "DateCompleted", 0x0C: "DueDate", 0x0D: "UtcDueDate",
        0x0E: "Importance", 0x0F: "Recurrence", 0x10: "Type",
        0x11: "Start", 0x12: "Until", 0x13: "Occurrences", 0x14: "Interval",
        0x15: "DayOfMonth", 0x16: "DayOfWeek", 0x17: "FirstDayOfWeek",
        0x18: "WeekOfMonth", 0x19: "MonthOfYear", 0x1A: "Regenerate",
        0x1B: "DeadOccur", 0x1C: "ReminderSet", 0x1D: "ReminderTime",
        0x1E: "Sensitivity", 0x1F: "StartDate", 0x20: "UtcStartDate",
        0x21: "Subject", 0x22: "Rtf", 0x23: "OrdinalDate",
        0x24: "SubOrdinalDate", 0x25: "CalendarType", 0x26: "IsLeapMonth",
        0x27: "FirstDayOfWeek", 0x28: "DueDate",
        # Extended tokens
        0x3F: "Status", 0x40: "PercentComplete", 0x41: "Sensitivity",
        0x42: "ReminderSet", 0x43: "ReminderTime", 0x44: "StartDate",
        0x45: "UtcStartDate", 0x46: "DueDate", 0x47: "UtcDueDate",
        0x48: "DateCompleted", 0x49: "Complete", 0x4A: "Recurrence",
        0x4B: "Subject", 0x4C: "Body", 0x4D: "BodySize",
        0x4E: "BodyTruncated", 0x4F: "Categories", 0x50: "Category",
        0x51: "Importance", 0x52: "Rtf", 0x53: "OrdinalDate",
        0x54: "SubOrdinalDate", 0x55: "CalendarType", 0x56: "IsLeapMonth",
        0x57: "FirstDayOfWeek", 0x58: "Type", 0x59: "Start",
        0x5A: "Until", 0x5B: "Occurrences", 0x5C: "Interval",
        0x5D: "DayOfMonth", 0x5E: "DayOfWeek", 0x5F: "WeekOfMonth",
        0x60: "MonthOfYear", 0x61: "Regenerate", 0x62: "DeadOccur",
    },
    # Page 10 - MeetingResponse
    10: {
        0x05: "MeetingResponse", 0x06: "Request", 0x07: "RequestType",
        0x08: "InstanceId", 0x09: "Response", 0x0A: "Status",
        0x0B: "CalendarId", 0x0C: "CollectionId", 0x0D: "RequestId",
        0x0E: "LongId", 0x0F: "InstanceId", 0x10: "UserResponse",
        0x11: "ProposedDuration",
    },
    # Page 11 - Email (Email2)
    11: {
        0x05: "UmCallerID", 0x06: "UmUserNotes", 0x07: "UmAttDuration",
        0x08: "UmAttOrder", 0x09: "ConversationId", 0x0A: "ConversationIndex",
        0x0B: "LastVerbExecuted", 0x0C: "LastVerbExecutionTime",
        0x0D: "ReceivedAsBcc", 0x0E: "Sender", 0x0F: "CalendarType",
        0x10: "IsLeapMonth", 0x11: "AccountId", 0x12: "FirstDayOfWeek",
        0x13: "MeetingMessageType", 0x14: "IsDraft",
    },
    # Page 12 - Notes (Email fields used in Sync)
    12: {
        0x05: "Subject", 0x06: "Body", 0x07: "BodySize",
        0x08: "BodyTruncated", 0x09: "Categories", 0x0A: "Category",
        0x0B: "LastModifiedDate",
    },
    # Page 15 - Search
    15: {
        0x05: "Search", 0x06: "Store", 0x07: "Name", 0x08: "Query",
        0x09: "Options", 0x0A: "Range", 0x0B: "Status", 0x0C: "Response",
        0x0D: "Result", 0x0E: "Properties", 0x0F: "Total", 0x10: "EqualTo",
        0x11: "Value", 0x12: "And", 0x13: "Or", 0x14: "FreeText",
        0x15: "DeepTraversal", 0x16: "LongId", 0x17: "RebuildResults",
        0x18: "LessThan", 0x19: "GreaterThan", 0x1A: "Schema",
        0x1B: "DocumentLibrary", 0x1C: "DocumentLibraryId",
        0x1D: "DocumentLibraryName", 0x1E: "DocumentLibraryUrl",
    },
    # Page 16 - GAL (Global Address List)
    16: {
        0x05: "DisplayName", 0x06: "Phone", 0x07: "Office",
        0x08: "Title", 0x09: "Company", 0x0A: "Alias", 0x0B: "FirstName",
        0x0C: "LastName", 0x0D: "HomePhone", 0x0E: "MobilePhone",
        0x0F: "EmailAddress", 0x10: "Picture", 0x11: "Status",
        0x12: "Data",
    },
    # Page 19 - ItemOperations
    19: {
        0x05: "ItemOperations", 0x06: "Fetch", 0x07: "Store",
        0x08: "Options", 0x09: "Range", 0x0A: "Total", 0x0B: "Response",
        0x0C: "Status", 0x0D: "Response", 0x0E: "Properties",
        0x0F: "Data", 0x10: "LongId", 0x11: "CollectionId",
        0x12: "ItemId", 0x13: "ByteRange", 0x14: "InstanceId",
        0x15: "FileReference", 0x16: "Schema", 0x17: "Part",
        0x18: "EmptyFolderContents", 0x19: "DeleteSubFolders",
        0x1A: "UserName",
    },
    # Page 21 - ComposeMail / SendMail / SmartForward / SmartReply
    21: {
        0x05: "SendMail", 0x06: "SmartForward", 0x07: "SmartReply",
        0x08: "SaveInSentItems", 0x09: "ReplaceMime", 0x0A: "Source",
        0x0B: "FolderId", 0x0C: "ItemId", 0x0D: "LongId",
        0x0E: "InstanceId", 0x0F: "MIME", 0x10: "ClientId",
        0x11: "Status", 0x12: "AccountId",
    },
    # Ping code page (13) - matches Exchange server response
    13: {
        0x05: "Ping",
        0x06: "AutdDiscover",
        0x07: "Status",
        0x08: "HeartbeatInterval",
        0x09: "Folders",
        0x0A: "Folder",
        0x0B: "Id",
        0x0C: "Class",
        0x0D: "MaxFolders",
    },
}
